function obj = GAopt(obj)
 
  range = [];

  for ii=1:length(obj.Ipara)
    range = [range; obj.Ipara{ii}];
  end

  for ii=1:length(obj.Cpara)
    range = [range; obj.Cpara{ii}];
  end
  lb = range(:,1); 
  ub = range(:,2);
  if obj.display ~=0
    options = gaoptimset('PopulationType', 'custom',...
                         'PopulationSize', obj.PopulationSize,...
                         'InitialPopulation', obj.IniPopulation,...
                         'PopInitRange', range',...
                         'CreationFcn', @CreateIC,...
                         'CrossoverFraction', obj.CrossoverRate,...
                         'MutationFcn', {@MutationIC, obj.MutationUniformRatio},...
                         'CrossoverFcn',@CrossoverIC,...
                         'Generations', obj.MaxGen,...
                         'TolFun', obj.toel,...
                         'PlotFcns', {@gaplotbestf, @gaplotscorediversity, @gaplotscores, @gaplotstopping});
  else
    options = gaoptimset('PopulationType', 'custom',...
                         'PopulationSize', obj.PopulationSize,...
                         'InitialPopulation', obj.IniPopulation,...
                         'PopInitRange', range',...
                         'CreationFcn', @CreateIC,...
                         'CrossoverFraction', obj.CrossoverRate,...
                         'MutationFcn', {@MutationIC, obj.MutationUniformRatio},...
                         'CrossoverFcn',@CrossoverIC,...
                         'Generations', obj.MaxGen,...
                         'TolFun', obj.toel,...
                         'Display', 'off');
  end


  Ipara = obj.Ipara;
  Cpara = obj.Cpara;
  Itype = obj.Itype;
  save GAinfor Ipara Cpara Itype
  
  if isempty(obj.FixedArgument)
    [para, fval, exitflag] = ga(obj.MyModel, size(range,1), [], [],[], [], lb,ub, [], options);
  else
    [para, fval, exitflag] = ga(@(x)obj.MyModel(x, obj.FixedArgument), size(range,1), [], [],[], [], lb,ub, [], options);
  end
  lenI = length(obj.Ipara);
  lenC = length(obj.Cpara);
  
  obj.output.Optimal_Ipara  = para(1:lenI);
  obj.output.Optimal_Cpara  = para(lenI+1:end);
  obj.output.Optimal_fval   = fval;

end